### PR TITLE
Infinex core v3 testnet deployment

### PR DESCRIPTION
**Pull request by rayInfinex**

### CODE REVIEW

**Comment by rayInfinex** [comment]
will update to add all other testnets soon

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/c72b6a9/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/c72b6a9/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/c72b6a9/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/ff1ccd6/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/ff1ccd6/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/ff1ccd6/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d0045f9/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d0045f9/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d0045f9/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/167aed9/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/167aed9/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/167aed9/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d47fb9f/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d47fb9f/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d47fb9f/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/7a54f62/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/7a54f62/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/7a54f62/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/2b3fbca/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/2b3fbca/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/2b3fbca/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/7d14bc4/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/7d14bc4/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/7d14bc4/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/cbddfc9/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/cbddfc9/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/cbddfc9/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/733d826/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/733d826/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/733d826/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/5ba5ffe/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/5ba5ffe/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/5ba5ffe/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/170225a/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/170225a/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/170225a/report/mainnets/

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d99726f/report/testnets/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d99726f/report/staging/
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/d99726f/report/mainnets/

**Review by ramboinfinex — CHANGES_REQUESTED** [review]
addresses.txt ? @axefinaxe

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/caffa29/report/testnets/
# Testnets Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 4:50:23 AM | 5.904 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

https://sys.infinex.xyz/reports/evm-contracts/deployments-test/caffa29/report/staging/
# Staging Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 4:50:23 AM | 4.672 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

https://sys.infinex.xyz/reports/evm-contracts/deployments-test/caffa29/report/mainnets/
# Mainnets Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 4:50:23 AM | 5.664 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/86ffa00/report/testnets/
# Testnets Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 4:52:08 AM | 4.504 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

https://sys.infinex.xyz/reports/evm-contracts/deployments-test/86ffa00/report/staging/
# Staging Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 4:52:09 AM | 4.899 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

https://sys.infinex.xyz/reports/evm-contracts/deployments-test/86ffa00/report/mainnets/
# Mainnets Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 4:52:09 AM | 4.136 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/3a6c9b5/report/testnets/
# Testnets Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 5:35:17 AM | 4.511 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

https://sys.infinex.xyz/reports/evm-contracts/deployments-test/3a6c9b5/report/staging/
# Staging Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 5:35:17 AM | 4.294 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

https://sys.infinex.xyz/reports/evm-contracts/deployments-test/3a6c9b5/report/mainnets/
# Mainnets Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 5:35:17 AM | 4.495 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

**Review by axefinaxe — APPROVED** [review]

**Comment by zeus-infinex** [comment]
https://sys.infinex.xyz/reports/evm-contracts/deployments-test/702456a/report/testnets/
# Testnets Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 6:44:18 AM | 4.67 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

https://sys.infinex.xyz/reports/evm-contracts/deployments-test/702456a/report/staging/
# Staging Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 6:44:18 AM | 4.863 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

https://sys.infinex.xyz/reports/evm-contracts/deployments-test/702456a/report/mainnets/
# Mainnets Report

| 🕙 Start time | ⌛ Duration |
| --- | ---: |
| 8/15/2024, 6:44:18 AM | 4.355 s |

| | ✅ Passed | ❌ Failed | ⏩ Skipped | 🚧 Todo | ⚪ Total |
| --- | ---: | ---: | ---: | ---: | ---: |
|Test Suites|2|1|0|0|3|
|Tests|10|0|0|0|10|

**Review by ramboinfinex — APPROVED** [review]

**Review by axefinaxe — APPROVED** [review]

**Pull request merged**
